### ISSUE TITLE
OpenID Connect 2.0.0 

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/openidconnect#104]
### Reason

- https://github.com/owncloud/openidconnect/pull/103 Azure AD: Use access token payload instead of user info endpoint
- https://github.com/owncloud/openidconnect/pull/112 Message: Object of class OCA\OpenIdConnect\Application could not be converted to string
- https://github.com/owncloud/openidconnect/pull/85 Import user from openid provider: Auto provisioning mode

### Product approval 

- [ ] Verify transifex commits are in master: If a folder https://github.com/owncloud/<APPNAME>/tree/master/l10n exists, then https://drone.owncloud.com/owncloud/<APPNAME> should receive nightly '[tx] updated from transifex` ...
- [x] Ping pmaier to check `info.xml` description and screenshot
- [ ] Get approval on translations from pmaier - send the date of the last tx commit from drone to Patrick

### QA

- [x] Generate Changelog
- [x] Create **QA** Milestone and set the description to $version
- [ ] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [x] Create "$version Testplan" https://github.com/owncloud/openidconnect/issues/132

### Documentation

- [x] :x: Changes in the docs needed? If so create issue in owncloud/docs. :x: -> https://github.com/owncloud/docs/pull/2447

### Marketing

- [x] Ping @owncloud/marketing

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [x] Check php version dependency in `info.xml`
- [x] Check minimum ownCloud version dependency in `info.xml`
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] Create github tag for `v${version}RC1` on release branch
- [x] Build and sign RC tarball from github tag `v${version}RC1` (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [ ] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries

### Publishing

- [x] Upload tarball to marketplace (see handbook in confluence for details)
- [x] Publish tarball for customers (see handbook in confluence for details) - https://customer.owncloud.com and https://portal.owncloud.com
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Copy email to rocket chat `#updates` channel

### Post-release

- [x] Rename QA milestone to `$version`
- [x] Add a new 'Unreleased' section in CHANGELOG.md (and also update links at the bottom!)
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number
- [x] Close the milestone
- [x] Ensure [release template](https://github.com/owncloud/handbook/edit/master/modules/ROOT/examples/releases/server_app_release_template.md) is up to date --> https://github.com/owncloud/administration-internal/pull/223

**Comment by DeepDiver1975** [comment]
https://github.com/owncloud/openidconnect/pull/103 is merged to master

**Comment by DeepDiver1975** [comment]
https://github.com/owncloud/openidconnect/pull/113 should be in 1.1.0 as well

**Comment by DeepDiver1975** [comment]
we have now auto provisioning in the pipeline as well #118 
@pmaier1 
- [ ] include auto provisioning in 1.1
- [ ] leave 1.1 for azure and do a 2.0 for auto provisioning
- [ ] do a 2.0 fr azure and auto provisioning

**Comment by pmaier1** [comment]
Nice! I think one release covering both would be great.

**Comment by pmaier1** [comment]
Any new config options in this release? https://github.com/owncloud/openidconnect/pull/118 mentions that the auto-provisioning needs to be **enabled**.

- [ ] Update documentation

**Comment by jnweiger** [comment]
## Issues opened while testing RC1

* #135 - [QA] Errors while enabling openidconnect-2.0.0RC1

**Comment by jnweiger** [comment]
### Issues opened while testing

* #138 [QA] autoprovisioning fails with 'picture-claim' => 'picture'

**Comment by jnweiger** [comment]
@pmaier1 @DeepDiver1975 
openidconnect-2.0.0RC1 pased QA. I'll tag it final and upload to github. 
For the next steps I need your help:
* Sync with Marketing, 
* push dcoumentation updates. (E.g. dynamic registration is not mentioned in  https://doc.owncloud.com/server/admin_manual/configuration/user/oidc/)

**Comment by DeepDiver1975** [comment]
>     * Dynamic client registration is not currently mentioned in the changelog. Should we?

no - because the server is not supporting client registration. This is a pure client thing ...

**Comment by michaelstingl** [comment]
Clients and IdP need to support dynamic client registration.

**Comment by jnweiger** [comment]
2.0.0 final is at github: https://github.com/owncloud/openidconnect/releases/tag/v2.0.0
