### ISSUE TITLE
error in using gluu as identity provider

### ISSUE THREAD

**Issue by otahmasebi** [owncloud/openidconnect#114]
I'm using GLUU as idp in my setup.
it's doing well with other applications i have.

OPENID CONNECT CLIENTS DETAILS in GLUU server
------------------------------
- **Name:** cl1.owti.ir
- **Client ID:** 9e59b137-6914-4777-b660-d6347e2418e9
- **Subject Type:** pairwise
- **ClientSecret:** XXXXXXXXXXX
- **Application Type:** web
- **Persist Client Authorizations:** true
- **Pre-Authorization:** false
- **Authentication method for the Token Endpoint:** client_secret_basic
- **Logout Session Required:** false
- **Include Claims In Id Token:** false
- **Disabled:** false
- **Logout Uri:** [https://cl1.owti.ir/apps/openidconnect/logout]
- **Login Redirect URIs:** [https://cl1.owti.ir/apps/openidconnect/redirect]
- **Scopes:** [profile, openid, email, user_name]
- **Grant types:** [authorization_code, refresh_token]
- **Response types:** [code]
----------------------------

i get this error after logging in:
```
Internal Server Error
The server encountered an internal error and was unable to complete your request.

Please contact the server administrator if this error reappears multiple times and include the technical details below in your report.

More details can be found in the server log.


Technical details
Remote Address: 5.160.86.250
Request ID: A9rRopOMuZwpxfNimKpr
Type: Jumbojett\OpenIDConnectClientException
Code: 0
Message: Error decoding JSON from token header
File: /var/www/owncloud/apps/openidconnect/vendor/jumbojett/openid-connect-php/src/OpenIDConnectClient.php
Line: 908

Trace
#0 /var/www/owncloud/apps/openidconnect/lib/SessionVerifier.php(120): Jumbojett\OpenIDConnectClient->verifyJWTsignature()
#1 /var/www/owncloud/apps/openidconnect/lib/Application.php(79): OCA\OpenIdConnect\SessionVerifier->verifySession()
#2 /var/www/owncloud/apps/openidconnect/appinfo/app.php(29): OCA\OpenIdConnect\Application->boot()
#3 /var/www/owncloud/apps/openidconnect/appinfo/app.php(30): OC_App::{closure}()
#4 /var/www/owncloud/lib/private/legacy/app.php(239): require_once('/var/www/ownclo...')
#5 /var/www/owncloud/lib/private/legacy/app.php(190): OC_App::requireAppFile()
#6 /var/www/owncloud/lib/private/legacy/app.php(124): OC_App::loadApp()
#7 /var/www/owncloud/lib/base.php(886): OC_App::loadApps()
#8 /var/www/owncloud/index.php(54): OC::handleRequest()
#9 {main}
```

**Comment by DeepDiver1975** [comment]
Looks like gluu is not using JWT as access tokens .....

You need to use the token introspection endpoint then ... no idea is gluu supports that ....

Feel free to provide the output of the service discovery information (if available under https://your.idp.net/.well-known/openid-configuration

**Comment by otahmasebi** [comment]
aha! i have to set Access Token as JWT.

this is my idp discovery information link:
[https://idp.danaholding.com/.well-known/openid-configuration](https://idp.danaholding.com/.well-known/openid-configuration)

I can customize my gluu server. I turned <Access Token as JWT> on in my gluu server, that fixed the error.

but now if I'm not logged in on idp.danaholding.com and cl1.owti.ir, when I try to login on cl1.owti.ir after redirecting from idp.danaholding.com I get this error on cl1.owti.ir:
```
Error in OpenIdConnect:Unable to determine state
```
But if I'm logged in on idp.danaholding.com, and not logged in in cl1.owti.ir, everything is fine, and there is no error after login request from cl1.owti.ir.

**Comment by DeepDiver1975** [comment]
Which browser are you using?

**Comment by otahmasebi** [comment]
Chrome Version 86.0.4240.111 (Official Build) (64-bit)
Firefox Version 82.0 (64-bit)

**Comment by otahmasebi** [comment]
if it help, this is my redirect url from idp.danaholding.com to cl1.owti.ir:

https://cl1.owti.ir/apps/openidconnect/redirect?code=65f7cb7c-ac97-4d55-97eb-83ee24cd33f7&scope=openid+profile+email&session_id=8341eddc-6e12-4bc4-a85d-f61efa5f9313&state=dceb955d391d05914908bab85faf7018&session_state=1257214232317d45059156efc78e8e7244fba5d2d1844a4c45f5b49c8cfdb410.b473de73-d667-4e6b-aa29-997ccef68a27

**Comment by DeepDiver1975** [comment]
This issue is related to the site cookie settings. It's a mess! 🙈
Comment this line https://github.com/owncloud/core/blob/4ce1d0ced1fb0d1451f7dee13dccd4ebc04a537c/lib/private/Session/CryptoWrapper.php#L102

**Comment by otahmasebi** [comment]
I also commented [https://github.com/owncloud/core/blob/4ce1d0ced1fb0d1451f7dee13dccd4ebc04a537c/lib/private/Session/CryptoWrapper.php#L101](https://github.com/owncloud/core/blob/4ce1d0ced1fb0d1451f7dee13dccd4ebc04a537c/lib/private/Session/CryptoWrapper.php#L101) and it fixed. thanks alot.

but there is three other things:
1. how can I define Post Logout Redirect Url
2. I have problem with "id_token_hint" in end_session request to idp, my idp said:
```
{
    "error_description": "The provided id token (or access token) or session state are invalid or were issued to another client.",
    "error": "invalid_grant_and_session"
}
```
, is there anyway to not include this in end_session request?
3. I want to create new users if they are not exist in owncloud local database, Is this possible?

**Comment by DeepDiver1975** [comment]
>  I want to create new users if they are not exist in owncloud local database, Is this possible?

see https://github.com/owncloud/openidconnect/issues/85 and #118

**Comment by DeepDiver1975** [comment]
>     1. I have problem with "id_token_hint" in end_session request to idp, my idp said:

the token is mandatory - question is:
- why is the token considered invalid?

Does the logout work anyways?

**Comment by otahmasebi** [comment]
> > I want to create new users if they are not exist in owncloud local database, Is this possible?
> 
> see #85 and #118
Tanks, i will check it.


> > ```
> > 1. I have problem with "id_token_hint" in end_session request to idp, my idp said:
> > ```
> 
> the token is mandatory - question is:
> 
> * why is the token considered invalid?
> 
> Does the logout work anyways?

I think it's a bug in gluu or maybe my configs, I'm sure that gluu does keep token of sessions itself and there is no need to send "id_token_hint" in end_session request. so I want to know if owncloud/openidconnect could send end_session request without any parameters in it.

**Comment by DeepDiver1975** [comment]
@otahmasebi I assume we can close this issue. If not let me know. THX
