### ISSUE TITLE
Desktop and mobile application login with openid

### ISSUE THREAD

**Issue by otahmasebi** [owncloud/openidconnect#127]
Hi,
my openid provider server is GLUU. everything is set and doing well, but i have problem in loging in into Desktop application and also mobile application. here in [#66](https://github.com/owncloud/openidconnect/issues/66#issuecomment-694087774) the webpage does show `Authorize` button to user, but in my case after opening and loging in into webpage the application just stuck and shows re-open webpage button and doing nothing.

[my .well-known url](https://idp.danaholding.com/.well-known/openid-configuration)

and my openidconnect configuration is like this:
```
'openid-connect' => 
  array (
    'loginButtonName' => 'Dana Holding',
    'provider-url' => 'https://idp.danaholding.com',
    'client-id' => '4640315a-XXX-c2c821500dcf',
    'client-secret' => 'XXXXXXXX',
    'post_logout_redirect_uri' => 'https://idp.danaholding.com/oxauth/restv1/end_session?post_logout_redirect_uri=https://cloud.danaholding.com
    'allowed-user-backends' => 
    array (
      0 => 'LDAP',
    ),
  ),
```

Also I have problem in creating new users, i have added these
```
'auto-provision' => [
      'enable' => true, 
      'email-claim' => 'email', 
      'display-name-claim' => 'name', 
      'picture-claim' => 'picture', 
    ]
```
to my config file, but owncloud shows this error after login for new users: `User with <new_user_email_address> is not known.`

**Comment by otahmasebi** [comment]
I solved my fist issue by installing [oAuth2](https://marketplace.owncloud.com/apps/oauth2) plugin on owncloud.
but my second problem that is creating new users is not solved.

**Comment by michaelstingl** [comment]
Creating new users on the fly will be solved with „auto provisioning“ feature in one of the next releases. There’s already a development branch: https://github.com/owncloud/openidconnect/pull/118

BTW there’s another Gluu related issue:
https://github.com/owncloud/openidconnect/issues/114

**Comment by DeepDiver1975** [comment]
#118 is merged -> closing
