### ISSUE TITLE
Owncloud-web only works in the same network where it runs

### ISSUE THREAD

**Issue by max-1004** [owncloud/openidconnect#133]
When I try to login to our owncloud from outside the host-network with the OIDC provider, than its not possible. When I press the button to login, the side loads and than stays at the same page. When I connect via VPN to the host network / go to office and use wlan it work fine. Also with the desktop, IOS and Android App it work fine. As redirect URL I use https://owncloud.example.de/apps/openidconnect/redirect . When I try for example https://owncloud.example.de/index.php/apps/openidconnect/redirect than I get an "invalid_request: given url is not allowed by the application configuration". My config.php is:

```
<?php
$CONFIG = array (
  'instanceid' => '516293f783096',
  'passwordsalt' => 'XXX',
  'secret' => 'aafa2f7a5574880745abb2f1285a4668248b5c3effe2dc3c52063801b82452e4bdcf293f8c50489a3b2aac1XXX',
  'trusted_domains' => 
  array (
    0 => 'owncloud.example.de'
  ),
  'datadirectory' => '/var/www/owncloud/data',
  #'overwrite.cli.url' => 'http://localhost',
  'htaccess.RewriteBase' => '/',
  'dbtype' => 'mysql',
  'version' => '10.5.0.10',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'XXX',
  'logtimezone' => 'UTC',
  'token_auth_enforced' => false,
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/owncloud/apps-external',
      'url' => '/apps-external',
      'writable' => true,
    ),
  ),
  'installed' => true,
  'maintenance' => false,
  'filelocking.enabled' => true,
  'openid-connect' => 
  array (
    'provider-url' => 'https://widas.cidaas.de',
    'client-id' => 'XXX',
    'client-secret' => 'XXX',
    'loginButtonName' => 'cidaas',
    'autoRedirectOnLoginPage' => false,
    'mode' => 'userid',
    'search-attribute' => 'email',
    'scopes' => 
    array (
      0 => 'openid',
      1 => 'email',
      2 => 'profile',
      3 => 'identities',
      4 => 'groups',
      5 => 'roles',
      6 => 'offline_access',
      7 => 'phone',
      8 => 'adress',
    ),
  ),
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'trashbin_retention_obligation' => 'auto',
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => 6379,
  ),
  'loglevel' => 2,
  'theme' => '',
  'singleuser' => false,
);
```
Does anyone have any idea what I need to change to get redirected even when I am not in the host network?

Thanks for help :)

**Comment by DeepDiver1975** [comment]
>  As redirect URL I use https://owncloud.example.de/apps/openidconnect/redirect . When I try for example https://owncloud.example.de/index.php/apps/openidconnect/redirect

- both urls are different -> this is where the error comes from
- you can register both uris as redirect urls in the idp
- or fix the owncloud setup so that index.php is no longer used (https://doc.owncloud.org/server/9.0/admin_manual/configuration_server/index_php_less_urls.html)

**Comment by max-1004** [comment]
I have tried it with both Uris in our IDP. But it is still the same. How can I change the redirect url of the button? The button I created for OIDC in config.php always has the url without index.php even if I change it in the IDP. 
I also followed the steps for "fix the owncloud setup so that index.php is no longer used", but I still have the same problem. To be honest, I don't understand why it works 100% fine in our network but not from outside.

**Comment by max-1004** [comment]
![Bildschirmfoto von 2021-01-20 09-40-02](https://user-images.githubusercontent.com/74765918/105149171-8b98ab80-5b03-11eb-985e-3681c7b1c85a.png)
Outside from the host network it looks like it work. It says redirect 302 but it stays on the same page...

**Comment by DeepDiver1975** [comment]
> 'provider-url' => 'https://widas.cidaas.de',

the idp is not accessible from the outside world ..... but it should ....

![Screenshot from 2021-01-20 12-45-07](https://user-images.githubusercontent.com/1005065/105170576-69138c00-5b1d-11eb-8fb9-1b420bb7ae4e.png)

**Comment by max-1004** [comment]
Thats not completely right.

Thats a normal behaviour from our side we are not exposing any UI or endpoint through this base path: https://widas.cidaas.de/
You can try to open this wellknown configuration endpoint: https://widas.cidaas.de/.well-known/openid-configuration
The OIDC configuration endpoint and all necessary services are reachable from the outside world.
Also the nginx is giving a proper and wanted 404 response.
I think thats not the problem

**Comment by max-1004** [comment]
The authorization URLs seems to be different from inside the network and outside of the host network (when I look with F12).
Inside the network:
GET https://widas.cidaas.de/authz-srv/authz?response_type=code&redirect_uri=https://owncloud.widas.de/apps/openidconnect/redirect&client_id=XXX&nonce=b6319a25219db247ddf18544c7f14710&state=496cca5f33744900fa5ccb378ad21bf6&scope=openid email profile identities groups roles offline_access phone adress openid

Outside:
https://owncloud.widas.de/authz-srv/authz?response_type=code&redirect_uri=https%3A%2F%2Fowncloud.widas.de%2Fapps%2Fopenidconnect%2Fredirect&client_id=XXXX&nonce=7b78917f1101342b5c77fc9120b4bd7c&state=5279c15d01b5e8f714f02798a53d6820&scope=openid+email+profile+identities+groups+roles+offline_access+phone+adress+openid

Do you know how to change it also from outside to widas.cidaas.de an not owncloud.widas.de?

**Comment by max-1004** [comment]
I made a little mistake, we get in both get requests as response from the redirect URL https://owncloud.widas.de/apps/openidconnect/redirect the same location. But only if we are in the same network as our server, we are then also redirected to the cidaas login page.

Inside the network:
Location: https://widas.cidaas.de/authz-srv/authz?response_type=code&redirect_uri=https%3A%2F%2Fowncloud.widas.de%2Fapps%2Fopenidconnect%2Fredirect&client_id=d349752d-9801-427c-9634-ac130577dcc9&nonce=d98a574b419bb3c13cdc06afdf1ea82b&state=08fc8bc7f8a2a3824f716af973f8c238&scope=openid+email+profile+identities+groups+roles+offline_access+phone+adress+openid

Outside:
Location: https://owncloud.widas.de/authz-srv/authz?response_type=code&redirect_uri=https%3A%2F%2Fowncloud.widas.de%2Fapps%2Fopenidconnect%2Fredirect&client_id=d349752d-9801-427c-9634-ac130577dcc9&nonce=0555a7490236cca370146507f4102ad9&state=e860af52452108a60ed212ab8666fc83&scope=openid+email+profile+identities+groups+roles+offline_access+phone+adress+openid

Do you have any idea why this is the case?

**Comment by max-1004** [comment]
Together with Christian Scherm and Erik Neubauer, I checked and changed the configuration. 
After the configuration changes, we finally got a 301 back with a curl -I https://owncloud.widas.de/.well-known/openid-configuration and no longer a 404.
![Bildschirmfoto von 2021-04-23 17-19-21](https://user-images.githubusercontent.com/74765918/115896528-cfc97e00-a45b-11eb-8b59-65a7098b54a2.png)
Here is a new config report
[widas_config_report_20210423.zip](https://github.com/owncloud/openidconnect/files/6366572/widas_config_report_20210423.zip)
With the new correct configuration we still get the same error as before
![Bildschirmfoto von 2021-04-23 17-51-00](https://user-images.githubusercontent.com/74765918/115897251-82014580-a45c-11eb-9f0c-68f9ba67ff56.png)

**Comment by DeepDiver1975** [comment]
closing under the assumption that this is solved by now
