### ISSUE TITLE
OIDC callback requests rely on SameSite: strict cookies which fails with cross domain IdP

### ISSUE THREAD

**Issue by longsleep** [owncloud/openidconnect#134]
This follows up https://github.com/owncloud/openidconnect/issues/123#issuecomment-760854250 as a new ticket.

ownCloud uses `SameSite: strict` on all cookies (https://github.com/owncloud/core/blob/736e54aa571658b9f1a31f9a27a3ff877b2a3006/lib/private/Session/CryptoWrapper.php#L102) which leads to no cookies being sent, when the OIDC callback comes back from the IdP (as a redirect to ownCloud) and that IdP is on another origin (not same site).

The callbacks for OIDC must when the initiating request is on another origin and thus having the callback rely on SameSite cookies does not work.

**Comment by DeepDiver1975** [comment]
I finally got back to this - sorry for the delay ....

As I did my tests around the samesite cookie and openid I did see the integration between owncloud and konnectd working even with the same site cookie in place.

I suspected that this is because the Sec-Fetch-Site header is in the redirect and I thought konnectd is setting it.
Which is not the case based on feedback by @longsleep 

I wonder where this header is coming from and if it really has an impact ....

**Comment by longsleep** [comment]
> I wonder where this header is coming from and if it really has an impact ....

@DeepDiver1975 the `Sec-Fetch-Site` header is set by the user agent automatically. It is used to let the server know how a client is treating a certain request. See https://bugs.chromium.org/p/chromium/issues/detail?id=843478

**Comment by DeepDiver1975** [comment]
I did not yet check the linked bug report ...

But why was it set with my kopano tests but not with e.g. azure/pingid?

Looks like I need to rerun my tests ....

**Comment by longsleep** [comment]
Well, those headers alone have no actual influence on the behavior described in this bug report. If you have a recent enough Chromium you see these headers all the time.

Like for example in one of my (ownCloud unrelated) tests:

```
sec-ch-ua: "Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"
sec-ch-ua-mobile: ?0
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-site
```

The browser just tells the server how it its going to treat this request.

**Comment by DeepDiver1975** [comment]
ok - so I was on the wrong track .....

as stated above - I need to rerun my tests .....

thx for the pointers @longsleep

**Comment by DeepDiver1975** [comment]
same site cookies can now be configured https://github.com/owncloud/core/pull/38458
