### ISSUE TITLE
[QA] Errors while enabling openidconnect-2.0.0RC1

### ISSUE THREAD

**Issue by jnweiger** [owncloud/openidconnect#135]
Within a docker-compose 10.6.0 server, 

* docker-compose exec owncloud bash
```
occ maintenance:mode --on
occ app:list openidconnect
```
```
    ownCloud is in maintenance mode - no app have been loaded
    Enabled:
      - openidconnect: 1.0.0
```  
```
occ app:disable openidconnect
cd custom
wget https://github.com/owncloud/openidconnect/releases/download/v2.0.0RC1/openidconnect-2.0.0RC1.tar.gz
tar xf openidconnect-2.0.0RC1.tar.gz
rm openidconnect-2.0.0RC1.tar.gz
chown -R www-data openidconnect
occ maintenance:mode --off
```
* From the admin settings web ui find the disabled openidconnect app, 
* verify that its version now shows 2.0.0, click 'enable'
* An error message appears (note: it complains about 'cannot disable' although I asked for enable):
![image](https://user-images.githubusercontent.com/1108546/105473138-0ba64900-5c9d-11eb-9940-5045e18744df.png)

Try the same with `occ app:enable openidconnect`
```
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
openidconnect enabled
```

Expected behaviour: Do not show an error, show the upgrade admin screen, when an upgrade is needed.

Workaround: run `occ upgrade` -- now the web ui and cli can enable/disable the app without errors.

**Comment by DeepDiver1975** [comment]
> occ app:disable openidconnect
> cd custom
> wget https://github.com/owncloud/openidconnect/releases/download/v2.0.0RC1/openidconnect-2.0.0RC1.tar.gz
> tar xf openidconnect-2.0.0RC1.tar.gz
> rm openidconnect-2.0.0RC1.tar.gz
> chown -R www-data openidconnect
> occ maintenance:mode --off

you are simply missing to run occ upgrade - unrelated to openidconnect -> close
