### ISSUE TITLE
[QA] autoprivosioning only adds user to one group

### ISSUE THREAD

**Issue by jnweiger** [owncloud/openidconnect#140]
Tested with openidconnect-2.0.0RC1 on oc-10.6.0 with php-7.4.3 connected against Azure AD

My test user at Azure AD is identified by juergen.weigert@owncloud.com
With autoprovisioning on, the user gets created in ownCloud. the groups setting is:

```
   'auto-provision' => [
        // defines a list of groups to which the newly created user will be added automatically
        'groups' => ['admin', 'guests', 'employees'],
```

The imported user is added only to the 'admin' group.
(One other user at the server is at least in group 'employees', so we know the group exists, if that is a precondition.)

![image](https://user-images.githubusercontent.com/1108546/105856601-b5613f00-5fe9-11eb-8166-843a1e1d3f7f.png)

Expected behaviour: the user gts added to all groups listed in the config.

**Comment by DeepDiver1975** [comment]
Do all groups exist in the system? 🙈

**Comment by jnweiger** [comment]
ok. understood. Groups are not autoprovisioned.

**Comment by michaelstingl** [comment]
Syncing full user directories, including groups, could be done with [SCIM]( https://openid.net/specs/openid-connect-scim-profile-1_0.html).
