### ISSUE TITLE
[QA] IDP certificate error causes a stack trace

### ISSUE THREAD

**Issue by jnweiger** [owncloud/openidconnect#141]
Tested with openidconnect-2.0.0RC1 on oc-10.6.0 with kopano konnect as IDP
Setup done via https://github.com/owncloud-docker/compose-playground/blob/master/examples/hetzner-deploy/make_openidconnect_test.sh

In this setup, caddy is used for ssh termination. It pulls two certificates from letsencrypt. Sometimes this fails due to ratelimits or similar.
When we have a certificate for owncloud server, but no certificate for kopano, internal errors occur, when ee.g. testing the .well-known/openid-configuration:

![Screenshot from 2021-01-28 09-19-14](https://user-images.githubusercontent.com/1108546/106111231-13a63300-614c-11eb-8cb0-74182994687f.png)

Expected behaviour: Proper error message without stack trace

**Comment by DeepDiver1975** [comment]
> Expected behaviour: Proper error message without stack trace

set debug to false in config.php - default behavior since years
