### ISSUE TITLE
Bearer authentication for CardDAV API with external auth server

### ISSUE THREAD

**Issue by mstilkerich** [owncloud/openidconnect#158]
Hello,

  I would like to use bearer authentication in the CardDAV API of owncloud. I have a keycloak authorization server that owncloud is connected to via this app. Login to the web interface of owncloud works fine. The DAV server advertises bearer authentication, but rejects the token for most requests.

I have an example log from a CardDAV addressbook discovery:

![Screenshot_20210524_085622](https://user-images.githubusercontent.com/3405515/119309052-0fa79f00-bc6e-11eb-811f-0de034db60e9.png)

First everything works as expected:
* 387 / 883: Unauthenticated PROPFIND on `/owncloud/remote.php/dav` is rejected, server advertises Basic and Bearer authentication in the WWW-Authenticate header
* 885 / 1642: Same PROPFIND request, now with Authorization: Bearer header. Now the request is replied to, and the principal URI `owncloud/remote.php/dav/principals/cloaky` is returned.
* Between 885/1642, we can see that owncloud checks with the keycloak server introspection and userinfo endpoints.

Now things don't work anymore:
* 1650/2225: Client tries a PROPFIND on the principal URI discovered above. Unauthenticated request is rejected as expected.
* 2227/2982: The authenticated request (same token / header as in 885) is rejected, interestingly with a 404. (Note: Basic auth to the same URI works just fine)

I would appreciate any insight on what goes wrong here. Is CardDAV access via bearer auth with external auth server supported at all?

**Comment by DeepDiver1975** [comment]
Generally speaking I'd suspect this to work. ownCloud Clients (android, ios, desktop and new web) are accessing dav resources using bearer token as well.

**Comment by DeepDiver1975** [comment]
I am suspecting a config issue with oc server. Please note that login via web ui uses a different flow as when a random token hits the server.

Closing this for the time being.
