### ISSUE TITLE
Error decoding JSON from token header

### ISSUE THREAD

**Issue by sidgangs99** [owncloud/openidconnect#165]
# Referred Thread: https://github.com/owncloud/openidconnect/issues/17

But was not able to resolve my issue.

### While implementing node-oidc provider, the auth workflow is implemented but at the last step, it displays error: 
```
Remote Address: 103.252.24.12
Request ID: QFb9UzXDpFx91gS9fBLn
Type: Jumbojett\OpenIDConnectClientException
Code: 0
Message: Error decoding JSON from token header
File: /var/www/owncloud/apps/openidconnect/vendor/jumbojett/openid-connect-php/src/OpenIDConnectClient.php
Line: 952

```
## Trace
```
Trace
#0 /var/www/owncloud/apps/openidconnect/lib/SessionVerifier.php(120): Jumbojett\OpenIDConnectClient->verifyJWTsignature()
#1 /var/www/owncloud/apps/openidconnect/lib/Application.php(79): OCA\OpenIdConnect\SessionVerifier->verifySession()
#2 /var/www/owncloud/apps/openidconnect/appinfo/app.php(28): OCA\OpenIdConnect\Application->boot()
#3 /var/www/owncloud/apps/openidconnect/appinfo/app.php(29): OC_App::{closure}()
#4 /var/www/owncloud/lib/private/legacy/app.php(253): require_once('/var/www/ownclo...')
#5 /var/www/owncloud/lib/private/legacy/app.php(192): OC_App::requireAppFile()
#6 /var/www/owncloud/lib/private/legacy/app.php(125): OC_App::loadApp()
#7 /var/www/owncloud/lib/base.php(885): OC_App::loadApps()
#8 /var/www/owncloud/index.php(54): OC::handleRequest()
#9 {main}

```
## Node-oidc Provider Conf:
```
https://github.com/panva/node-oidc-provider/blob/main/example/support/configuration.js
```
### Is this a bug ?

**Comment by DeepDiver1975** [comment]
What does the token look like?

**Comment by PaulaFernandez** [comment]
I am having what I think are similar problems trying to use Google OpenID.

My configuration is:

```
'http.cookie.samesite' => 'None',
'openid-connect' =>
    array (
      'auto-provision' =>
        array (
          'enabled' => false,
        ),
      'provider-url' => 'https://accounts.google.com',
      'client-id' => 'secret-id',
      'client-secret' => 'secret',
      'loginButtonName' => 'Google',
      'mode' => 'email',
      'post_logout_redirect_uri' => 'https://owncloud.colorifix.com',
    ),

```

And the error I am getting originates in line 122 in OpenIDConnectClient.php

```
if (!$client->verifyJWTsignature($accessToken)) {
    $this->logger->error('Token cannot be verified: ' . $accessToken);
    $this->logout();
    throw new OpenIDConnectClientException('Token cannot be verified.');
}
```

and following that:


**Google accessToken is not a JWT and hence it cannot be decoded.** 

I saw it the documentation that if the access token is not a JWT token we could use:

> use-token-introspection-endpoint - if set to true the token introspection endpoint is used to verify a given access token - only needed if the access token is not a JWT
> 
> token-introspection-endpoint-client-id & token-introspection-endpoint-client-secret - client id and secret to be used with the token introspection endpoint

but I have no idea what those values might be.

**Comment by dschmidt** [comment]
If I interpret the README of node-oidc correctly, it implements the token introspection endpoint. (c.f. https://github.com/panva/node-oidc-provider/blob/72d6ca639340c9a9868bf07b65d80f029c52d1bb/README.md?plain=1#L28)

Check if `introspection_endpoint` is provided in `.well-known/openid-configuration` and if not if it either needs to be enabled or you just need to add that key+value to your configuration if you're not using the .well-known file.

**Comment by dschmidt** [comment]
... and you also need to explicitly enable using of the introspection endpoint:
```
  'openid-connect' => [
    ...
    'use-token-introspection-endpoint' => true,
    'provider-params' => [
      ...
      'introspection_endpoint' => 'yoururl
    ],
  ],
```
