### ISSUE TITLE
Release openidconnect 2.1.0

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/openidconnect#168]
### Reason

#148 [Security] Bump phpseclib/phpseclib from 2.0.29 to 2.0.31 
#150 [Enhancement] AutoProvisioning based on a Provisioning Claim
#151 [Enhancement] Autoprovisionining based on claim
#155 [Bugfix] Use random_bytes for uid and password generation
#167 [Enhancement] Add db as additional settings storage backend

Release is required (mainly because of #167 ) for use in ownCloud Online.

### Product approval 

- [ ] Verify transifex commits are in master: If a folder https://github.com/owncloud/<APPNAME>/tree/master/l10n exists, then https://drone.owncloud.com/owncloud/<APPNAME> should receive nightly '[tx] updated from transifex` ...
- [ ] Ping pmaier to check `info.xml` description and screenshot
- [ ] Get approval on translations from pmaier - send the date of the last tx commit from drone to Patrick

### QA

- [x] Create **QA** Milestone and set the description to $version
- [ ] Move tickets from milestone `development` to `qa` (testplan and tickets mentioned in release ticket)
- [x] Create release branch with the format "release-$version"
- [x] Create "$version Testplan"  -> #179
- [ ] copy new/reopened issues from the previous release ticket as 'Issues to review' below.
- [x] check if [Non-normal Release Process](https://confluence.owncloud.com/display/OG/Apps+with+differences+in+release+process) applies, and adapt this checklist.

### Documentation

- [ ] Changes in the docs needed? If so create issue in owncloud/docs.

### Marketing

- [ ] Ping @owncloud/marketing
- [ ] Update https://confluence.owncloud.com/display/PROD/Upcoming+Releases
- [ ] Request a screenshot if the app is new or changed fundamentally

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [x] Bump "sonar.projectVersion=" in `sonar-project.properties` (no version suffix)
- [x] Check php version dependency in `info.xml`
- [x] Check minimum ownCloud version dependency in `info.xml`
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] Ping product owner to create github tag for `v${version}-rc1` on release branch (see https://confluence.owncloud.com/display/EN/Product+Owners+List)
- [x] Build and sign RC tarball from github tag `v${version}-rc1` (see handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Manual testing (changelog, regression, explorative):
    - [x] If this is an enterprise app: Enabling the app must start the grace period
    - [x] If this is the initial release of an app: Check that the minimum version constraint resolves correctly
    - [x] Changelog testing
    - [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch
       - [x] server + web ui + desktop regression tests
       - [x] android regression tests
       - [x] ios regression tests

#### Final

- [x] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries
- [x] Ping `#marketing` channel to coordinate publishing

### Publishing

- [x] Upload tarball to marketplace (see handbook in confluence for details)
- [x] Publish tarball for customers  - [old 10](https://customer.owncloud.com/owncloud/index.php/apps/files/?dir=%2FownCloud-Enterprise%2FownCloud-10), [old 10.0](https://customer.owncloud.com/owncloud/index.php/apps/files/?dir=%2FownCloud-Server%2FownCloud-10.0) and [new portal](https://portal.owncloud.com/apps/files/?dir=/Portal%20Data/All%20Account%20Data/ownCloud%20Enterprise%20Resources%20Data/Server&fileid=5661) (see [handbook](https://confluence.owncloud.com/display/OG/Releasing+Apps) for details)
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Copy email to rocket chat `#updates` channel

### Post-release

- [x] Add a new 'Unreleased' section in CHANGELOG.md (and also update links at the bottom!)
- [x] Create PR to merge changes back to the `master` branch with description "Closes #XYZ" with the release ticket number
- [x] Rename QA milestone to `$version` and close the milestone
- [x] Update https://confluence.owncloud.com/display/PROD/Upcoming+Releases
- [x] Ensure [release template](https://github.com/owncloud/administration-internal/edit/master/tools/release/templates/server_app_release_template.md) is up to date
- [x] Ensure the testplan template ([community](https://github.com/owncloud/QA/tree/master/Server) or [enterprise](https://github.com/owncloud/qa-enterprise/tree/master/Core)) is up to date
- [x] Close the testplan issue

**Comment by jnweiger** [comment]
Testplan draft: https://github.com/owncloud/openidconnect/issues/132
Please ping me for additions, I'll make a niche testplan from that.

**Comment by hurradieweltgehtunter** [comment]
@jnweiger Testplan needs the following additions regarding #167 
For other PR's we need to ask PR creators
@IljaN @T0mWz @DeepDiver1975 could you please give information about PR's #148 #150 #151 #155 ?

# Add no settings at all
- Enable app
- Test login

## Expected behaviour
App fails the same way as previous release

# Add no settings to DB
- Add valid settings to config.php (default way, not altered)
- Remove any existing config settings in DB
- Enable app
- Test login

## Expected behaviour
Login should work

# Add invalid settings to DB
- Add valid settings to config.php (default way, not altered)
- Add settings to DB as stated in Readme (https://github.com/owncloud/openidconnect#settings-in-database) but use a malformed JSON string
- Enable app
- Test login

## Expected behaviour
- Login should work
- ownCloud.log should contain an error message, see https://github.com/owncloud/openidconnect/blob/fd9ae9e09a670c5473b349247239e84dc0bb82f5/lib/Client.php#L102

# Add valid settings to DB
- Add settings to DB as stated in Readme (https://github.com/owncloud/openidconnect#settings-in-database)
- Enable app
- Test login

## Expected behaviour
Login should work

**Comment by jnweiger** [comment]
@hurradieweltgehtunter can you provide test instances fro the above issues?

**Comment by hurradieweltgehtunter** [comment]
I don't have access to set up public instances, Sorry.

**Comment by hurradieweltgehtunter** [comment]
Is this going forward? Anything I can do to speed this up?

**Comment by michaelstingl** [comment]
> Is this going forward? Anything I can do to speed this up?

No progress. Blocked by other priorities and vacations.

**Comment by DeepDiver1975** [comment]
Also an important change in this release which needs to go out - https://github.com/owncloud/openidconnect/pull/130

**Comment by T0mWz** [comment]
@jnweiger what information is required for #150 #151 ?
had described this little bit in issue https://github.com/owncloud/openidconnect/issues/149, but maybe it's to short or more info required. Please let me know, you can also find me on Rocket Chat. 😃

**Comment by jnweiger** [comment]
RC1 created: https://github.com/owncloud/openidconnect/releases/download/v2.1.0-rc1/openidconnect-2.1.0-rc1.tar.gz

**Comment by DeepDiver1975** [comment]
Most recent tests with openidconnect app (git master) have shown that PKCE is not properly working.
Upstream fix is pending at the moment: https://github.com/jumbojett/OpenID-Connect-PHP/pull/273

Affected IdPs: any who supports PKCE or enforces it.

**Comment by jnweiger** [comment]
## Issues opened while testing
* [ ] https://github.com/owncloud/openidconnect/issues/181

**Comment by jnweiger** [comment]
RC2 built. It includes the fix for #181

**Comment by jnweiger** [comment]
RC2 passed changelog tests and server/desktop regression tests.
Android & iOS: TODO
