### ISSUE TITLE
Error messages should be more informative

### ISSUE THREAD

**Issue by thommierother** [owncloud/openidconnect#172]
Error messages based on curl commands should display the actual curl target URL. This helps in debugging a oidc setup. See https://central.owncloud.org/t/10-8-oidc-openidconnect-curl-error-self-signed-certificate-in-certificate-chain/33425/6 for reference
![Screenshot_20210806_202010](https://user-images.githubusercontent.com/6594120/128671463-c278853d-478b-40a7-b47b-b8fbc322aeae.png)

**Comment by DeepDiver1975** [comment]
Exposing such information could be considered an information disclosure and will at least make white hat hackers to know at our door. 

Adding the url to the log file sounds reasonable ....
