### ISSUE TITLE
json not delivered on index.php/apps/openidconnect/config

### ISSUE THREAD

**Issue by thommierother** [owncloud/openidconnect#173]
On a freshly set-up 10.8 I can not get any OIDC config json. A curl request is answered with 

< HTTP/1.1 200 OK

but the reply is empty. And even on log level 0 there is no error visible in the owncloud.log . 
The test system:

curl -v https://owncloud2.netzwissen.de/index.php/apps/openidconnect/config -H "Accept: application/json"

How can I debug this?

**Comment by DeepDiver1975** [comment]
If the connected IdP is not exposing and openid-configuration - we are not doing either .....

please make sure the IdP has an openid-configuration.

**Comment by thommierother** [comment]
fixed,idp was misconfigured
