### ISSUE TITLE
Update user information during logging in

### ISSUE THREAD

**Issue by milkydan** [owncloud/openidconnect#187]
We are using openidconnect app in CESNET ownCloud instance. We found out, that the current version does not update user information (such as preferred email) provided by IdP.  It updates preferred email only during creating a new user. Is it possible to support this workflow in a future release op openidconnect app?  Thanks.

**Comment by alex-metcalfe-358** [comment]
Are we able to update group membership information somehow?

**Comment by DeepDiver1975** [comment]
With azuread you can hook up owncloud with ad via ldap and you don't need auto provisioning.
user and group infromations are retrieved then via ldap from ad
