### ISSUE TITLE
provisioning-claim and provisioning-attribute not documented

### ISSUE THREAD

**Issue by stefanost67** [owncloud/openidconnect#202]
We see that the provisioning-claim and provisioning-attribute configuration sub-keys are not documented. 
We need them in order to allow access only to members of certain groups.

Are you going to maintain and document the usage of these keys?

**Comment by michaelstingl** [comment]
@mmattel @EParzefall FYI

**Comment by stefanost67** [comment]
We also noticed that, if we use something like:

               'provisioning-attribute' => 'my_group',
               'provisioning-claim' => 'groups'

users are still given access if they leave my_group

Do you have any policy regarding this?

**Comment by IljaN** [comment]
@stefanost67 Those claims are part of "auto-provisioning": i.e. if the ownCloud sees the user coming from the IDP for the first time the user is provisioned in ownCloud. If the claim is removed user still exists in ownCloud and thus is able to login.

**Comment by stefanost67** [comment]
Ok, thanks for the information.
What about supporting the provisioning attribute and claim keys? Can they be used in production?

**Comment by IljaN** [comment]
Yes, they are already used in production by some users. We will document them asap. Will post a link here to preliminary documentation.

**Comment by IljaN** [comment]
Found an existing docs-issue here: https://github.com/owncloud/docs/issues/3502

Is more input needed?

**Comment by stefanost67** [comment]
This is exactly our use case. We are able to use these feature, including using the groups claim in order to limit access only to a subset of users, so our questions are answered. 
What we wanted to make sure is that these features will be supported in the future and can be used in production environments, without having to worry about them disappearing in future versions of the plugin.

**Comment by IljaN** [comment]
@mmattel Edited the [top-post](https://github.com/owncloud/docs/issues/3502) here to make it more clear.
