### ISSUE TITLE
Public Link Uploads Fail for Anonymous Users

### ISSUE THREAD

**Issue by tryton-vanmeer** [owncloud/openidconnect#203]
When creating and sharing a public link, an anonymous user is unable to upload any files.

If I disable the openidconnect app then uploading as an anonymous user works.

I've attached a log file with the exception that occurs when performing the steps below.

[owncloud.log](https://github.com/owncloud/openidconnect/files/8015927/owncloud.log)

# Steps to Reproduce

1. In OwnCloud, select a folder to share and create a public link
2. Select `Upload only (File Drop)` and share
3. Copy the public link
4. Open in a browser session where you're not logged into the OwnCloud server
5. Try to upload a file

# System Details

OwnCloud Server (Docker image): 10.9.0
OpenID Connect: v2.1.0

**Comment by jnweiger** [comment]
Confirmed fixed in 2.1.1-rc1

**Comment by voroyam** [comment]
@jnweiger is there an ETA of the 2.1.1?

**Comment by voroyam** [comment]
ah, sorry. got it from here. is the target still in reach?

https://github.com/owncloud/enterprise/issues/5024#issuecomment-1051097172

```
I'll target 2022-03-07 -- if all goes well. Upcoming releases page updated accordingly.
```
