### ISSUE TITLE
Release Openidconnect 2.1.1

### ISSUE THREAD

**Issue by IljaN** [owncloud/openidconnect#208]
### Reason

- Fix https://github.com/owncloud/openidconnect/issues/203 https://github.com/owncloud/openidconnect/pull/195 
- Fix https://github.com/owncloud/openidconnect/pull/200 
- Regular Maintenance (Library updates)

### Product approval 

- [ ] Verify transifex commits are in master: If a folder https://github.com/owncloud/<APPNAME>/tree/master/l10n exists, then https://drone.owncloud.com/owncloud/<APPNAME> should receive nightly '[tx] updated from transifex` ...
- [ ] Ping pmaier to check `info.xml` description and screenshot
- [ ] Get approval on translations from pmaier - send the date of the last tx commit from drone to Patrick

### QA

- [x] Create **QA** Milestone and set the description to $version
- [x] Move tickets from milestone `development` to `qa` (testplan and tickets mentioned in release ticket)
- [x] Create release branch with the format "release-$version"
- [x] Create "$version Testplan" -> #210
- [ ] copy new/reopened issues from the previous release ticket as 'Issues to review' below.
- [x] check if [Non-normal Release Process](https://confluence.owncloud.com/display/OG/Apps+with+special+release+process) applies, and adapt this checklist.

### Documentation

- [ ] Changes in the docs needed? If so create issue in owncloud/docs.

### Marketing

- [ ] Ping @owncloud/marketing
- [x] Update https://confluence.owncloud.com/display/PROD/Upcoming+Releases
- [x] Request a screenshot if the app is new or changed fundamentally

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [x] Bump "sonar.projectVersion=" in `sonar-project.properties` (no version suffix)
- [x] Check php version dependency in `info.xml`
- [x] Check minimum ownCloud version dependency in `info.xml`
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] Ping product owner to create github tag for `v${version}-rc1` on release branch (see https://confluence.owncloud.com/display/EN/Product+Owners+List)
- [x] Build and sign RC tarball from github tag `v${version}-rc1` (see handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan + manual explorative testing:
    - [x] If this is an enterprise app: Enabling the app must start the grace period
    - [x] Add section "Changlog Testing" using github releases text or CHANGELOG.md from release branch
    - [x] Do changelog tests
    - [x] Do regression tests
    - [x] => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [ ] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries

### Publishing

- [x] Upload tarball to marketplace (see handbook in confluence for details)
- [x] Publish tarball for customers  - [old 10](https://customer.owncloud.com/owncloud/index.php/apps/files/?dir=%2FownCloud-Enterprise%2FownCloud-10), [old 10.0](https://customer.owncloud.com/owncloud/index.php/apps/files/?dir=%2FownCloud-Server%2FownCloud-10.0) and [new portal](https://portal.owncloud.com/apps/files/?dir=/Portal%20Data/All%20Account%20Data/ownCloud%20Enterprise%20Resources%20Data/Server&fileid=5661) (see [handbook](https://confluence.owncloud.com/display/OG/Releasing+Apps) for details)
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Copy email to rocket chat `#updates` channel

### Post-release

- [x] Add a new 'Unreleased' section in CHANGELOG.md (and also update links at the bottom!)
- [x] Create PR to merge changes back to the `master` branch with description "Closes #XYZ" with the release ticket number
- [x] Rename QA milestone to `$version` and close the milestone
- [x] Update https://confluence.owncloud.com/display/PROD/Upcoming+Releases
- [x] Ensure [release template](https://github.com/owncloud/QA/edit/master/tools/release/templates/server_app_release_template.md) is up to date
- [x] Ensure the testplan template ([community](https://github.com/owncloud/QA/tree/master/Server) or [enterprise](https://github.com/owncloud/qa-enterprise/tree/master/Core)) is up to date
- [x] Close the testplan issue

**Comment by IljaN** [comment]
```
{"reqId":"YhUq8rJAbz97jcIVJXTxYQAAAAM","level":0,"time":"2022-02-22 18:26:58.197200","remoteAddr":"62.216.205.40","user":"--","app":"OpenID","method":"GET","url":"\/index.php\/apps\/openidconnect\/redirect","message":"Entering LoginFlowController::login"}
{"reqId":"YhUq8rJAbz97jcIVJXTxYQAAAAM","level":0,"time":"2022-02-22 18:26:58.197500","remoteAddr":"62.216.205.40","user":"--","app":"OpenID","method":"GET","url":"\/index.php\/apps\/openidconnect\/redirect","message":"Before openid->authenticate"}
{"reqId":"YhUq97JAbz97jcIVJXTxYgAAAAM","level":0,"time":"2022-02-22 18:27:03.199800","remoteAddr":"62.216.205.40","user":"--","app":"OC\\Authentication\\Token\\DefaultTokenProvider::invalidateToken","method":"GET","url":"\/index.php\/apps\/openidconnect\/redirect?state=2a02ba55c36e4f4916819a6f622b5507&session_state=099f2438-6390-48d0-9eef-96255724d7ea&code=ee4787b8-e309-47c8-8cc6-0805b07d5031.099f2438-6390-48d0-9eef-96255724d7ea.b9710b51-2a97-49cf-aeca-db891121841e","message":"invalidating token 2b28fc5d7d2b624e8a4ed58dd45d9036467d645fc640ef0ec137360652c459b4b674b2346b63a9b098c239a46711f581d2cb555590b300ab2b724ab3ce745e77"}
{"reqId":"YhUq97JAbz97jcIVJXTxYgAAAAM","level":2,"time":"2022-02-22 18:27:03.211400","remoteAddr":"62.216.205.40","user":"--","app":"user_ldap","method":"GET","url":"\/index.php\/apps\/openidconnect\/redirect?state=2a02ba55c36e4f4916819a6f622b5507&session_state=099f2438-6390-48d0-9eef-96255724d7ea&code=ee4787b8-e309-47c8-8cc6-0805b07d5031.099f2438-6390-48d0-9eef-96255724d7ea.b9710b51-2a97-49cf-aeca-db891121841e","message":"Configuration Error (prefix ): login filter does not contain %uid place holder."}
{"reqId":"YhUq97JAbz97jcIVJXTxYgAAAAM","level":2,"time":"2022-02-22 18:27:03.211800","remoteAddr":"62.216.205.40","user":"--","app":"user_ldap","method":"GET","url":"\/index.php\/apps\/openidconnect\/redirect?state=2a02ba55c36e4f4916819a6f622b5507&session_state=099f2438-6390-48d0-9eef-96255724d7ea&code=ee4787b8-e309-47c8-8cc6-0805b07d5031.099f2438-6390-48d0-9eef-96255724d7ea.b9710b51-2a97-49cf-aeca-db891121841e","message":"Configuration Error (prefix ): login filter does not contain %uid place holder."}
{"reqId":"YhUq97JAbz97jcIVJXTxYgAAAAM","level":2,"time":"2022-02-22 18:27:03.220100","remoteAddr":"62.216.205.40","user":"--","app":"user_ldap","method":"GET","url":"\/index.php\/apps\/openidconnect\/redirect?state=2a02ba55c36e4f4916819a6f622b5507&session_state=099f2438-6390-48d0-9eef-96255724d7ea&code=ee4787b8-e309-47c8-8cc6-0805b07d5031.099f2438-6390-48d0-9eef-96255724d7ea.b9710b51-2a97-49cf-aeca-db891121841e","message":"Configuration Error (prefix ): login filter does not contain %uid place holder."}
{"reqId":"YhUq97JAbz97jcIVJXTxYgAAAAM","level":0,"time":"2022-02-22 18:27:03.220800","remoteAddr":"62.216.205.40","user":"--","app":"OpenID","method":"GET","url":"\/index.php\/apps\/openidconnect\/redirect?state=2a02ba55c36e4f4916819a6f622b5507&session_state=099f2438-6390-48d0-9eef-96255724d7ea&code=ee4787b8-e309-47c8-8cc6-0805b07d5031.099f2438-6390-48d0-9eef-96255724d7ea.b9710b51-2a97-49cf-aeca-db891121841e","message":"Entering LoginFlowController::login"}
{"reqId":"YhUq97JAbz97jcIVJXTxYgAAAAM","level":0,"time":"2022-02-22 18:27:03.221000","remoteAddr":"62.216.205.40","user":"--","app":"OpenID","method":"GET","url":"\/index.php\/apps\/openidconnect\/redirect?state=2a02ba55c36e4f4916819a6f622b5507&session_state=099f2438-6390-48d0-9eef-96255724d7ea&code=ee4787b8-e309-47c8-8cc6-0805b07d5031.099f2438-6390-48d0-9eef-96255724d7ea.b9710b51-2a97-49cf-aeca-db891121841e","message":"Before openid->authenticate"}
{"reqId":"YhUq97JAbz97jcIVJXTxYgAAAAM","level":3,"time":"2022-02-22 18:27:04.713900","remoteAddr":"62.216.205.40","user":"--","app":"OpenID","method":"GET","url":"\/index.php\/apps\/openidconnect\/redirect?state=2a02ba55c36e4f4916819a6f622b5507&session_state=099f2438-6390-48d0-9eef-96255724d7ea&code=ee4787b8-e309-47c8-8cc6-0805b07d5031.099f2438-6390-48d0-9eef-96255724d7ea.b9710b51-2a97-49cf-aeca-db891121841e","message":"Exception: {\"Exception\":\"JuliusPC\\\\OpenIDConnectClientException\",\"Message\":\"PKCE code verifier not specified\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/local\\\/src\\\/owncloud\\\/custom\\\/openidconnect\\\/lib\\\/Client.php(206): JuliusPC\\\\OpenIDConnectClient->authenticate()\\n#1 \\\/usr\\\/local\\\/src\\\/owncloud\\\/custom\\\/openidconnect\\\/lib\\\/Controller\\\/LoginFlowController.php(125): OCA\\\\OpenIdConnect\\\\Client->authenticate()\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(170): OCA\\\\OpenIdConnect\\\\Controller\\\\LoginFlowController->login(*** sensitive parameters replaced ***)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\OpenIdConnect\\\\Controller\\\\LoginFlowController), 'login')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(100): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\OpenIdConnect\\\\Controller\\\\LoginFlowController), 'login')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\OpenIdConne...', 'login', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(343): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(927): OC\\\\Route\\\\Router->match('\\\/apps\\\/openidcon...')\\n#8 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#9 {main}\",\"File\":\"\\\/usr\\\/local\\\/src\\\/owncloud\\\/custom\\\/openidconnect\\\/vendor\\\/juliuspc\\\/openid-connect-php\\\/src\\\/OpenIDConnectClient.php\",\"Line\":339}"}

```

**Comment by stijnbrouwers** [comment]
This release should also include the fix for #194, right?

**Comment by jnweiger** [comment]
Issues seen while testing
* [ ] https://github.com/owncloud/openidconnect/issues/212
* [ ]

**Comment by mmattel** [comment]
With this upcoming release, is there anything docs relevant?
