### ISSUE TITLE
[QA] complicated recovery after error messges

### ISSUE THREAD

**Issue by jnweiger** [owncloud/openidconnect#213]
Seen with openidconnect 2.1.1 RC1 and openidconnect 2.1.0 on core 10.9.1

While testing different IDPs and differnt modes (autprovisioning, or not, ...)
several error messages happend during login attempts. The errors are correct, but the form they are presented could be improved.
E.g.

![image](https://user-images.githubusercontent.com/1108546/156424808-28e91cc8-ae97-4621-a709-e1a0dfb7af43.png)

![image](https://user-images.githubusercontent.com/1108546/156424798-eef99fbd-e7cf-4a10-9d14-00a8097a23cc.png)

In all cases, the admin user wants to log in, and adjust settings, or in case of the reddemd token, it is sufficient that the user tries again.

This is cumbersome, as it involves not only clearing cookies from the local browser cache, but also manual URL editing (remove token query parameters), in order to get back to a clean login page.

Enhancement idea:
* add a link to the login form to this error page, if needed with a special parameter to invalidate the session. 
  (similar to the logout-redirect-url that is used, when a user properly logs out from the idp)

**Comment by jnweiger** [comment]
Example of the lengthy URL:
![image](https://user-images.githubusercontent.com/1108546/156580628-d597d7ce-836c-4f05-87e8-9a1d36a1f9b6.png)

**Comment by DeepDiver1975** [comment]
> Enhancement idea:
> 
>     * add a link to the login form to this error page, if needed with a special parameter to invalidate the session.
>       (similar to the logout-redirect-url that is used, when a user properly logs out from the idp)

core issue.

for anything else: well - this is the pain of integration :shrug:

**Comment by jnweiger** [comment]
When user chooses `cancel` at the idp:
![image](https://user-images.githubusercontent.com/1108546/193787621-d783ca9f-b149-4a57-a3f8-476a8d7b2e83.png)
