### ISSUE TITLE
[QA] Allow ownCloud step is missing when using Azure

### ISSUE THREAD

**Issue by jnweiger** [owncloud/openidconnect#214]
Seen in 2.1.1.-rc1 (not yet tested with 2.1.0)

* user clocks the Azure (oidc) button, and authenticates with Microsoft.
![image](https://user-images.githubusercontent.com/1108546/156582528-208d58d0-48f4-4d3d-b354-e53e1232216a.png)
----
* Microsoft pops up another 'stay signed in' dialog -> choose any.
![image](https://user-images.githubusercontent.com/1108546/156582690-a95178fb-223b-451c-af73-088b22bf1818.png)
----
* The user is immediately logged into owncloud
![image](https://user-images.githubusercontent.com/1108546/156582783-ad89476c-9c6e-469d-b1de-2e5b0aa76472.png)

Expected behaviour:
* As with e.g. Kopano, there is an extra page, where the user authorizes ownCloud to access his data.
![image](https://user-images.githubusercontent.com/1108546/156583151-7460602a-e107-4e3a-8cd6-f465d78dbe02.png)

**Comment by DeepDiver1975** [comment]
different idps have different behavior aka look into config options of the idp. not in control of owncloud -> close

**Comment by jnweiger** [comment]
There is a "onstent", with a consent name "ownCloud" configured:

![image](https://user-images.githubusercontent.com/1108546/156595968-745055b9-8482-4090-bb4d-f0a9ceea0ee3.png)

I cannot decide, if this is not showing due to a misconfiguration on my behalf, due to a bug in our code, or if this is normal behaviour.
