### ISSUE TITLE
PKCE error with cookie.samesite

### ISSUE THREAD

**Issue by tbs575** [owncloud/openidconnect#219]
https://github.com/owncloud/openidconnect/issues/218#issue-1166047800 
as using docker owncloud, so add one more config file

```
<?php
$CONFIG = [
  'http.cookie.samesite' => 'None',
  'openid-connect' => [
     'provider-url' => 'https://xxxxxxxxxxxx/auth/realms/icep',
     'client-id' => 'owncloud',
     'client-secret' => 'xxxxxxxxxxxxxx',
     'loginButtonName' => 'Login via xxxxxxxxx',
     'frontchannel_logout_session_required' => true,
     'insecure' => true,
     'auto-provision' => [
      // explicit enable the auto provisioning mode
      'enabled' => true,
      // documentation about standard claims: https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims
      // only relevant in userid mode,  defines the claim which holds the email of the user
      'email-claim' => 'email',
      // defines a list of groups to which the newly created user will be added automatically
      'groups' => ['guests', 'employees'],
    ]
  ]
];
```
but still PKCE error

**Comment by DeepDiver1975** [comment]
after changing the cookie settings it is absolutly necesssary to ensure that the existing sessions are gone:
- kill all browsers
- kill all sessions server side

**Comment by DeepDiver1975** [comment]
(no need to open a new issue - we could continue in the previous one)

**Comment by tbs575** [comment]
@DeepDiver1975 thanks your reply, but still error
I restart owncloud service, clean all history data with browser, no working. 

if no SSL, can login owncloud with keycloak (openid),

**Comment by tbs575** [comment]
@DeepDiver1975 thanks your reply, as you suggestion. and Now, can not login, still error
![image](https://user-images.githubusercontent.com/30616402/157826012-494880e9-e413-48ba-9ee5-124636083593.png)

**Comment by tbs575** [comment]
Using SSL just for owncloud desktop, it seemed owncloud desktop client did not support  http protocol.
