### ISSUE TITLE
Configurable IP address in docker-compose test environment

### ISSUE THREAD

**Issue by felix-schwarz** [owncloud/openidconnect#22]
The current docker-compose test environment is limited to be used on `localhost` out of the box. It would be useful for QA and testing on mobile devices to have an easy way to set up a docker-based test server without having to manually change configuration files.

To make the OIDC and OC instances available on the IP `10.0.1.69`, I had to make the following changes to the configuration files:

```diff
diff --git a/tests/docker/node-oidc/configuration.js b/tests/docker/node-oidc/configuration.js
index bf149dc..1f44998 100644
--- a/tests/docker/node-oidc/configuration.js
+++ b/tests/docker/node-oidc/configuration.js
@@ -16,8 +16,15 @@ module.exports = Object.assign({
       client_id: 'ownCloud',
       client_secret: 'ownCloud',
       grant_types: ['refresh_token', 'authorization_code'],
-      redirect_uris: ['http://10.254.254.254:8080/apps/openidconnect/redirect'],
-      frontchannel_logout_uri: 'http://10.254.254.254:8080/apps/openidconnect/logout'
+      redirect_uris: ['http://10.0.1.69:8080/apps/openidconnect/redirect'],
+      frontchannel_logout_uri: 'http://10.0.1.69:8080/apps/openidconnect/logout'
+    },
    {
diff --git a/tests/docker/owncloud/oidc.config.php b/tests/docker/owncloud/oidc.config.php
index 002ed9d..53ef0db 100644
--- a/tests/docker/owncloud/oidc.config.php
+++ b/tests/docker/owncloud/oidc.config.php
@@ -1,7 +1,7 @@
 <?php
 $CONFIG = [
        'openid-connect' => [
-               'provider-url' => 'http://10.254.254.254:3000',
+               'provider-url' => 'http://10.0.1.69:3000',
                'client-id' => 'ownCloud',
```

The change to the URLs in the configuration files are necessary to achieve the goal, because they become part of server responses and are pointing to IPs unreachable by other devices by default.

If making the IP configurable proves too much hassle or effort, it'd be nice to at least have instructions included, to help testers in need of such a setup to get an instance up and running quickly.

/cc @michaelstingl @jesmrec

**Comment by DeepDiver1975** [comment]
Is this still of interest?please reopen then. Thx
