### ISSUE TITLE
openidconnect 2.2.0

### ISSUE THREAD

**Issue by jnweiger** [owncloud/openidconnect#241]
### Reason

- PR owncloud/openidconnect#222 fixes owncloud/openidconnect#187
- PR owncloud/openidconnect#247 fixes owncloud/openidconnect#246
- owncloud/openidconnect#272 

### Product approval 

- [ ] Verify transifex commits are in master: If a folder https://github.com/owncloud/<APPNAME>/tree/master/l10n exists, then https://drone.owncloud.com/owncloud/<APPNAME> should receive nightly '[tx] updated from transifex` ...
- [ ] Ping pmaier to check `info.xml` description and screenshot
- [ ] Get approval on translations from pmaier - send the date of the last tx commit from drone to Patrick

### QA

- [x] Create **QA** Milestone and set the description to $version
- [x] Move tickets from milestone `development` to `qa` (testplan and tickets mentioned in release ticket)
- [x] Create release branch with the format "release-$version"
- [x] Create "2.2.0 Testplan" --> owncloud/openidconnect#240  ([QA templates](https://github.com/owncloud/QA/tree/master/Server) or [Enterprise](https://github.com/owncloud/qa-enterprise/tree/master/Core))
- [ ] copy new/reopened issues from the previous release ticket as 'Issues to review' below.
- [x] check if [Non-normal Release Process](https://confluence.owncloud.com/display/OG/Apps+with+special+release+process) applies, and adapt this checklist.

### Documentation

- [ ] Changes in the docs needed? If so create issue in owncloud/docs-server.

### Marketing

- [ ] Ping @owncloud/marketing
- [x] Update https://confluence.owncloud.com/display/PROD/Upcoming+Releases
- [ ] Request a screenshot if the app is new or changed fundamentally

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [x] Bump "sonar.projectVersion=" in `sonar-project.properties` (no version suffix)
- [x] Check php version dependency in `info.xml`
- [x] Check minimum ownCloud version dependency in `info.xml`
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [ ] Ping product owner to create github tag for `v${version}-rc1` on release branch (see https://confluence.owncloud.com/display/EN/Product+Owners+List)
- [x] Build and sign RC tarball from github tag `v${version}-rc1` (see handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan + manual explorative testing:
    - [x] If this is an enterprise app: Enabling the app must start the grace period
    - [x] Add section "Changlog Testing" using github releases text or CHANGELOG.md from release branch
    - [x] Do changelog tests
    - [x] Do regression tests
    - [x] => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [ ] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries

### Publishing

- [x] Upload tarball to marketplace (see handbook in confluence for details)
- [x] Publish tarball for customers  - [old 10](https://customer.owncloud.com/owncloud/index.php/apps/files/?dir=%2FownCloud-Enterprise%2FownCloud-10), [old 10.0](https://customer.owncloud.com/owncloud/index.php/apps/files/?dir=%2FownCloud-Server%2FownCloud-10.0) and [new portal](https://portal.owncloud.com/apps/files/?dir=/Portal%20Data/All%20Account%20Data/ownCloud%20Enterprise%20Resources%20Data/Server&fileid=5661) (see [handbook](https://confluence.owncloud.com/display/OG/Releasing+Apps) for details)
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Copy email to rocket chat `#updates` channel

### Post-release

- [x] Add a new 'Unreleased' section in CHANGELOG.md (and also update links at the bottom!)
- [ ] Create PR to merge changes back to the `master` branch with description "Closes #XYZ" with the release ticket number
- [ ] Rename QA milestone to `$version` and close the milestone
- [x] Update https://confluence.owncloud.com/display/PROD/Upcoming+Releases
- [x] Ensure [release template](https://github.com/owncloud/QA/edit/master/tools/release/templates/server_app_release_template.md) is up to date
- [x] Ensure the testplan template ([community](https://github.com/owncloud/QA/tree/master/Server) or [enterprise](https://github.com/owncloud/qa-enterprise/tree/master/Core)) is up to date
- [x] Close the testplan issue

**Comment by DeepDiver1975** [comment]
Please make sure to create the release branch from the correct commit. I merged a bunch of prs which are not for this release.

Thx

**Comment by DeepDiver1975** [comment]
Actually this commit should be fine
https://github.com/owncloud/openidconnect/commit/94fcbc37d6a697521a2ffa462f758cda1e2ce154

**Comment by jnweiger** [comment]
> Please make sure to create the release branch from the correct commit. I merged a bunch of prs which are not for this release.
> 
> Thx

Between https://github.com/owncloud/openidconnect/commit/94fcbc37d6a697521a2ffa462f758cda1e2ce154
and head of master, there are only library bumps and compose updates. Nothing worth avoiding. I am puzzled.

From my POV, we can also have https://github.com/owncloud/openidconnect/pull/243 in this release.

**Comment by DeepDiver1975** [comment]
regression reported: https://github.com/owncloud/openidconnect/issues/246

**Comment by DeepDiver1975** [comment]
needs to be incorporated into the next rc https://github.com/owncloud/openidconnect/pull/247 @jnweiger

**Comment by jnweiger** [comment]
Included in https://github.com/owncloud/openidconnect/releases/tag/v2.2.0-rc.2 - Thanks!

**Comment by jnweiger** [comment]
## Issues seen while Testing
* [ ] https://github.com/owncloud/openidconnect/issues/248

**Comment by DeepDiver1975** [comment]
include https://github.com/owncloud/openidconnect/issues/254

**Comment by phil-davis** [comment]
Note: PR #222 added a parameter `autoProvisioningService` to the constructor of LoginFlowController

https://github.com/owncloud/openidconnect/blob/master/lib/Controller/LoginFlowController.php#L84

That class is used/extended in https://github.com/owncloud/msteamsbridge and so the code in that app needed a matching change. See issue https://github.com/owncloud/msteamsbridge/issues/37 which is fixed in PR https://github.com/owncloud/msteamsbridge/pull/36

I think that https://github.com/owncloud/msteamsbridge will need to be released "in sync" with https://github.com/owncloud/openidconnect (or some further code changes made somewhere that auto-detect what parameters to pass to the constructor or...)

**Comment by jnweiger** [comment]
https://github.com/owncloud/openidconnect/releases/tag/v2.2.0-rc.7

**Comment by jnweiger** [comment]
QA passed with several minor defects, see above.
