### ISSUE TITLE
App access with openid-connect in owncloud

### ISSUE THREAD

**Issue by mano87** [owncloud/openidconnect#244]
We use this connector in conjunction with a Keycloak service. The login works very well from the PC.

Is it necessary that a new client with secure and ID is stored in Keycloak for the ownCloud app from iOS or Android? We receive the error message from the Keycloak service that the client was not found.

Is this then identical for all service IDs provided via the Keycloak service?

**Comment by DeepDiver1975** [comment]
please find this described in https://doc.owncloud.com/server/next/admin_manual/configuration/user/oidc/oidc.html#owncloud-desktop-and-mobile-clients

in case of further questions: https://central.owncloud.org/

THX
