### ISSUE TITLE
PKCE code verifier not specified

### ISSUE THREAD

**Issue by WYmindsky** [owncloud/openidconnect#249]
openidconnect: 2.1.0
keycloak: 8.0
owncloud: 9.0.1

I can input username and password (all right)
![图片](https://user-images.githubusercontent.com/20678602/186096590-acbc0d65-b9be-4d56-b6a2-ccd3c2abb083.png)

then redirect new url and get error: Error in OpenConnect: PKCE code verifier not specified
![图片](https://user-images.githubusercontent.com/20678602/186096727-611cf937-9ce6-46cc-b484-81d15f015a26.png)

this is config.php
`'http.cookie.samesite' => 'None',
  'openid-connect' => [
    'insecure' => true,
    'frontchannel_logout_session_required' => true,
    'provider-url' => 'http://example.com/auth/realms/myrealm',
    'client-id' => 'owncloud',
    'client-secret' => 'xxxx',
    'loginButtonName' => 'OpenId Connect',
  ],
`

**Comment by michaelstingl** [comment]
Duplicate for https://github.com/owncloud/openidconnect/issues/218 ?

**Comment by WYmindsky** [comment]
> Duplicate for #218 ?

i set in config.php, but still error.
'http.cookie.samesite' => 'None'

**Comment by DeepDiver1975** [comment]
Usually this error continues to exist if the session was created BEFORE the cookie setting was changed in ownCloud.
Sessions need to be fully deleted on server side.
