### ISSUE TITLE
[QA] desktop client does not start oidc flow

### ISSUE THREAD

**Issue by jnweiger** [owncloud/openidconnect#251]
Seen with openidconnect-2.2.0-rc.3 on server 10.11.0-rc.2 using desktop client 2.11.1

* Setup server with kopao idp
* login admin via web ui and normal login button. Works. OK.
* login aaron_beer via web ui and kopano button. Works. OK.
* start desktop client and add the server url.
* The client prompts for username and password. BAD.
* kopano user aaron_beer can log in with his password. Strange. 

Expected behaviour:
* after entering the server url, the client opens a browser window to the kopano IDP
* login credentials are not entered into the client.

Regression:
* openidconnect-2.1.0 on server 10.11.0-rc.2 using desktop client 2.11.1 starts the oidc flow correctly.

Test systems:
- https://oc10110rc2-oidc-210-20220916.jw-qa.owncloud.works
- https://oc10110rc2-oidc-220rc3-20220916.jw-qa.owncloud.works

**Comment by DeepDiver1975** [comment]
Not working because we send 
```
www-authenticate: Bearer/PoP realm="ownCloud"
```

which is not understood by the client ....

![Screenshot from 2022-09-19 21-38-46](https://user-images.githubusercontent.com/1005065/191101350-e81d09b2-7ba3-4c45-8c75-e78a0fce1626.png)

**Comment by jnweiger** [comment]
Confirmed fixed:
* Client 2.11.1,   Server 10.11 with openidconnect 2.2.0-rc.6 and keycloak.
