### ISSUE TITLE
[QA] admin cannot login, when basic_auth_guest_only is true

### ISSUE THREAD

**Issue by jnweiger** [owncloud/openidconnect#261]
Seen while testing openidconnect 2.2.0-rc.6 with core 10.11.0

* Restrict basic auth to guests only: `occ config:system:set openid-connect.basic_auth_guest_only --value true --type boolean`
* Try to log in the admin user with basic auth. 
* An error occurs. BAD
![image](https://user-images.githubusercontent.com/1108546/193918151-bd43b4bf-20fe-4192-981b-ab2732c720fc.png)

Expected behaviour:
* admin can always log in.

**Comment by DeepDiver1975** [comment]
Works as designed. Only guests 🤷

**Comment by DeepDiver1975** [comment]
I suggest to revert https://github.com/owncloud/openidconnect/pull/253 and get this release rolling.

We have customers waiting for other features of this release.

@jvillafanez @hodyroff @jnweiger objections

**Comment by jvillafanez** [comment]
https://github.com/owncloud/openidconnect/pull/265 would fix this, but we need to decide what to do with the feature as a whole

**Comment by DeepDiver1975** [comment]
Absolutly

- blocking/allowing guest login is not the responsibility of the openid connect app from my pov
- adding yet another config switch #265 might be a bit overkill - only one customer is requesting this feature
- lack of decision making is blocking other customers

**Comment by DeepDiver1975** [comment]
revert pr created ...... so that we are prepares once the decision is there ..... https://github.com/owncloud/openidconnect/pull/268

**Comment by jnweiger** [comment]
I agree with the revert and move everything to work with groups. #265 could carry guests and admin group to fix my case.
The naming of the key in #265 is weird then and should be simplified.

**Comment by jnweiger** [comment]
@DeepDiver1975 
I cannot confirm that the code is working with 2.2.0-rc.7

* `occ config:system:set openid-connect.basic_auth_guest_only --value true --type boolean`
* Now only admin and guests should be able to log in via basic auth.
* user einstein is neither admin group nor guests group, and can log in. BAD.
*

**Comment by DeepDiver1975** [comment]
We removed this feature. It will be implemented in core. Out of scope
