### ISSUE TITLE
Does not work if config added *after* install, or maybe has error.  Had to reinstall to make it work again.  Suggest making it automatically re-enable?

### ISSUE THREAD

**Issue by ZacharyACoon** [owncloud/openidconnect#312]
Owncloud 10.14, latest openid-connect in market.

**Comment by DeepDiver1975** [comment]
Not really an issue in the software from what I can tell - please seek out for community support on https://central.owncloud.org/ - THX

**Comment by ZacharyACoon** [comment]
It is an issue if it error's silently and there's no indication as to what
to do.
