### ISSUE TITLE
Third-Party Cookies and Front-Channel-Logout

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/openidconnect#35]
This is basically to document relevant information for devs.

According to https://bitbucket.org/openid/connect/issues/1003/document-possible-impacts-of-disabling the front-channel-logout cannot work as soon as the browser disallows third-party-cookies.

No idea if we can detect this and work around .... at least this has to be double checked in cases where the logout is not working

**Comment by mmattel** [comment]
Is this something to be mentioned in the (dev) docs?

**Comment by DeepDiver1975** [comment]
> Is this something to be mentioned in the (dev) docs?

no - this issue as reminder is enough

**Comment by DeepDiver1975** [comment]
solved by setting the samesite cookie options in config.php
