### ISSUE TITLE
How to install this onto my owncloud instance?

### ISSUE THREAD

**Issue by suhaylhallim** [owncloud/openidconnect#74]
I couldn't find information on how to install this app onto my instance of owncloud.

**Comment by DeepDiver1975** [comment]
Did you have a look in the online Docs?
We have a section there.

**Comment by suhaylhallim** [comment]
Thank you for your responce and, sorry for the late reply. Maybe I'm not looking properly? I only found information on how to configure the app in the owncloud config file. Doesn't this app need to be install as a third-party app i.e. download and copy the app to the external_apps in the owncloud dir before configuring? If I'm misunderstanding something, please clarify. 

best regards.

**Comment by suhaylhallim** [comment]
I've solved this problem.

**My current Setup**
x64 Windows 10 Laptop (Used for remote access and development)
x64 Putty for Windows
x64 Git for Windows
Composer for Windows
Any FTP Windows Application(For transferring the files to my remote Linux server)

**Disclaimer**
While I'm sure you can do the following in windows CMD, I didn't try because I had git bash readily available on my computer for obvious reasons.

**General steps to install this app unto OwnCloud**
Step 1 : Clone this repo either with git or simply download this project 
Step 2 : Extract the project (if not already extracted)
Step 3 : Copy the "composer.phar" file to the root of this project folder
Step 4 : Open GIT BASH in the root of this project folder by right-clicking.
Step 5 : Run the following command in order to get all the required files for this project "php composer.phar install"
Step 6 : Open a ftp connection to the owncloud server.
Step 7 : Copy this project folder to the server.
Step 7 : Using putty to ssh into the server, copy the project folder to the "owncloud/apps-external" location.
Step 8 : Rename the project folder to the app name "openidconnect" and give it and its content the appropriate permission for user:group i.e www-data:www-data.
Step 9 : Follow the instruction on this github readme page in order to configure.
