### ISSUE TITLE
How to authorize client app

### ISSUE THREAD

**Issue by suhaylhallim** [owncloud/openidconnect#80]
How do i authroize client apps i.e. windows desktop client and android client app while this app is setup and functional?

I can sign in using the web browser. When I enter the url of my owncloud instance in the desktop client, it opens the browser for me to login. Once login, it goes to the the file app and the client app is never authorized. If I click "re-open browser" I'm taken to an already logged in session. Nothing happens.

**Comment by michaelstingl** [comment]
@suhaylhallim this is the issue tracker of the ownCloud 10 OpenID Connect app, not a help forum. Please use https://central.owncloud.org/ instead.
